services:
    db:
        image: postgres:13
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_NAME: ${POSTGRES_NAME}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
    
    emitter:
        env_file:
            - .env
        environment:
            DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_NAME}
        build:
            context: .
            dockerfile: ./emitter/Dockerfile 
        restart: always

    client:
        env_file:
            - .env
        build:
            context: ./client
        ports:
            - 3000:3000
        

volumes:
    postgres-data:
