services:
  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  emitter:
    env_file:
      - .env
    environment:
      DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_NAME}
    build:
      context: .
      dockerfile: ./emitter/Dockerfile
    restart: always

  client:
    env_file:
      - .env
    build:
      context: ./client
    ports:
      - 3000:3000

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis/data
    restart: always
    command: redis-server --timeout 0 --tcp-keepalive 300

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - UPLOADS_DIR=${UPLOADS_DIR:-/usr/app/uploads}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8000:8000
      - 50051:50051
    volumes:
      - ./uploads:/usr/app/uploads
    depends_on:
      - db
      - redis

volumes:
  postgres-data:
  redis-data:
